---
title: "02_estimate_MPEC_kernel"
author: "Suguru Otani"
date: "2024-01-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load {.tabset}

```{r, echo=FALSE,results = "asis"}
rm(list = ls())
library(magrittr)
library(ggplot2)
library(modelsummary) # for N in datasummary

results_MPEC_consumer_1000_error_draw_100_scaling_2_2_2 <-
  readr::read_csv(file = here::here("output/results_MPEC_consumer_1000_error_draw_100_scaling_-2-2-2.csv"),
                  col_names = FALSE) %>% 
  dplyr::mutate(
    filename = "results_MPEC_consumer_1000_error_draw_100_scaling_-2-2-2"
  ) %>% 
  dplyr::filter(
    X8 == "LOCALLY_SOLVED"
    )
results_MPEC_consumer_1000_error_draw_100_scaling_5_5_5 <-
  readr::read_csv(file = here::here("output/results_MPEC_consumer_1000_error_draw_100_scaling_-5-5-5.csv"),
                  col_names = FALSE) %>% 
  dplyr::mutate(
    filename = "results_MPEC_consumer_1000_error_draw_100_scaling_-5-5-5"
  ) %>% 
  dplyr::filter(
    X8 == "LOCALLY_SOLVED"
    )
results_MPEC_consumer_1000_error_draw_100_scaling_20_20_20 <-
  readr::read_csv(file = here::here("output/results_MPEC_consumer_1000_error_draw_100_scaling_-20-20-20.csv"),
                  col_names = FALSE) %>% 
  dplyr::mutate(
    filename = "results_MPEC_consumer_1000_error_draw_100_scaling_-20-20-20"
  ) %>% 
  dplyr::filter(
    X8 == "LOCALLY_SOLVED"
    )
results_MPEC_consumer_1000_error_draw_100_scaling_18_4_7 <-
  readr::read_csv(file = here::here("output/results_MPEC_consumer_1000_error_draw_100_scaling_-18-4-7.csv"),
                  col_names = FALSE) %>% 
  dplyr::mutate(
    filename = "results_MPEC_consumer_1000_error_draw_100_scaling_-18-4-7"
  ) %>% 
  dplyr::filter(
    X8 == "LOCALLY_SOLVED"
    )
results_MPEC_consumer_1000_error_draw_100_scaling_50_50_50 <-
  readr::read_csv(file = here::here("output/results_MPEC_consumer_1000_error_draw_100_scaling_-50-50-50.csv"),
                  col_names = FALSE) %>% 
  dplyr::mutate(
    filename = "results_MPEC_consumer_1000_error_draw_100_scaling_-50-50-50"
  ) %>% 
  dplyr::filter(
    X8 == "LOCALLY_SOLVED"
    )
true_parameter <-
  c(
    1.0,
    0.7,
    0.5,
    0.3,
    -3.0
  )
# results_kernel <-
#   readr::read_csv(file = here::here("output/results_kernel.csv"),
#                   col_names = FALSE) %>% 
#   dplyr::mutate(
#     filename = "results_kernel"
#   ) 

```


## Results {.tabset}

### results_MPEC_consumer_1000_error_draw_100_scaling_18_4_7 (Ursu et al 2023)

```{r,echo=FALSE,results = "asis"}
modelsummary::datasummary_skim(results_MPEC_consumer_1000_error_draw_100_scaling_18_4_7)
```


### results_MPEC_consumer_1000_error_draw_100_scaling_2_2_2

```{r,echo=FALSE,results = "asis"}
modelsummary::datasummary_skim(results_MPEC_consumer_1000_error_draw_100_scaling_2_2_2)
```

### results_MPEC_consumer_1000_error_draw_100_scaling_5_5_5

```{r,echo=FALSE,results = "asis"}
modelsummary::datasummary_skim(results_MPEC_consumer_1000_error_draw_100_scaling_5_5_5)
```

### results_MPEC_consumer_1000_error_draw_100_scaling_20_20_20

```{r,echo=FALSE,results = "asis"}
modelsummary::datasummary_skim(results_MPEC_consumer_1000_error_draw_100_scaling_20_20_20)
```

### results_MPEC_consumer_1000_error_draw_100_scaling_50_50_50

```{r,echo=FALSE,results = "asis"}
modelsummary::datasummary_skim(results_MPEC_consumer_1000_error_draw_100_scaling_50_50_50)
```